// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/irahardianto/service-pattern-go/models"

// IPlayerRepository is an autogenerated mock type for the IPlayerRepository type
type IPlayerRepository struct {
	mock.Mock
}

// CreatePlayer provides a mock function with given fields: player
func (_m *IPlayerRepository) CreatePlayer(player models.PlayerModel) (bool, error) {
	ret := _m.Called(player)

	var r0 bool
	if rf, ok := ret.Get(0).(func(models.PlayerModel) bool); ok {
		r0 = rf(player)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.PlayerModel) error); ok {
		r1 = rf(player)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePlayer provides a mock function with given fields: id
func (_m *IPlayerRepository) DeletePlayer(id int) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPlayers provides a mock function with given fields:
func (_m *IPlayerRepository) GetAllPlayers() []models.PlayerModel {
	ret := _m.Called()

	var r0 []models.PlayerModel
	if rf, ok := ret.Get(0).(func() []models.PlayerModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerModel)
		}
	}

	return r0
}

// GetPlayerById provides a mock function with given fields: id
func (_m *IPlayerRepository) GetPlayerById(id int) models.PlayerModel {
	ret := _m.Called(id)

	var r0 models.PlayerModel
	if rf, ok := ret.Get(0).(func(int) models.PlayerModel); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.PlayerModel)
	}

	return r0
}

// GetPlayerMessageFromAPI provides a mock function with given fields:
func (_m *IPlayerRepository) GetPlayerMessageFromAPI() models.MessageModel {
	ret := _m.Called()

	var r0 models.MessageModel
	if rf, ok := ret.Get(0).(func() models.MessageModel); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MessageModel)
	}

	return r0
}

// UpdatePlayer provides a mock function with given fields: id, player
func (_m *IPlayerRepository) UpdatePlayer(id int, player models.PlayerModel) (bool, error) {
	ret := _m.Called(id, player)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, models.PlayerModel) bool); ok {
		r0 = rf(id, player)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, models.PlayerModel) error); ok {
		r1 = rf(id, player)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
