// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/irahardianto/service-pattern-go/models"

// IPlayerRepository is an autogenerated mock type for the IPlayerRepository type
type IPlayerRepository struct {
	mock.Mock
}

// GetPlayerByName provides a mock function with given fields: name
func (_m *IPlayerRepository) GetPlayerByName(name string) (models.PlayerModel, error) {
	ret := _m.Called(name)

	var r0 models.PlayerModel
	if rf, ok := ret.Get(0).(func(string) models.PlayerModel); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(models.PlayerModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerMessageFromAPI provides a mock function with given fields:
func (_m *IPlayerRepository) GetPlayerMessageFromAPI() models.MessageModel {
	ret := _m.Called()

	var r0 models.MessageModel
	if rf, ok := ret.Get(0).(func() models.MessageModel); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MessageModel)
	}

	return r0
}
